# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'rosademo1'
    cmd: 'oc project myapp'
  displayName: Switch to myapp project
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'rosademo1'
    cmd: 'oc new-app https://github.com/sgkevinye/simple-app'
    ignoreFlag: true
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'rosademo1'
    cmd: 'oc expose svc simple-app'
    ignoreFlag: true
  displayName: Create route
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'rosademo1'
    cmd: 'oc start-build simple-app --follow'
  displayName: Start new build
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'rosademo1'
    cmd: 'oc status'
